### ISSUE TITLE
 Unexpected token ... in debug.js:17

### ISSUE THREAD

**Issue by Om-KSPL** [dferber90/jsdom-screenshot#2] opened 2018-12-21 13:14 UTC
When I install this I am getting error. My node version is v8.2.1
```
/Users/om/Documents/projects/odoo/ekogrid/npms/node_modules/jsdom-screenshot/debug.js:17
    ...options
    ^^^

SyntaxError: Unexpected token ...
```

**Comment by dferber90** [comment] 2018-12-21 15:04
Thanks for the report! This is fixed in [v3.1.1](https://github.com/dferber90/jsdom-screenshot/releases/tag/v3.1.1).

Would you mind explaining your use-case for `jsdom-screenshot`?  Just playing around or something more serious?

**Closed as completed by dferber90** 2018-12-21 15:04 UTC

**Comment by Om-KSPL** [comment] 2018-12-24 05:59
Thanks, I was just doing a POC to download an image of a page.

**Comment by dferber90** [comment] 2018-12-24 09:36
Cool! I wouldn't recommend trying to build your own Visual Regression Testing solution as one tends to run into false negatives due to differences in font rendering, animations and other things. I went down that route myself and eventually settled on using a CI service to do so. Both [Percy](https://www.chromaticqa.com/) and [Chormatic](https://www.chromaticqa.com/) seem like good solutions if you want to build something more serious 👍
